### ISSUE TITLE
[Bug]: getting pdf is not a function

### ISSUE THREAD

**Issue by advany** [cloudflare/puppeteer#13]
### Bug description

Calling page.pdf() causes this error

### Puppeteer version

latest

### Node.js version

latest

### npm version

latest

### What operating system are you seeing the problem on?

macOS

**Comment by rvlzzr** [comment]
a workaround would be:
```
declare module "@cloudflare/puppeteer" {
  interface Page {
    pdf(options?: puppeteer.PDFOptions): Promise<Buffer>;
  }
}
```

**Comment by meddulla** [comment]
This has been fixed. Please install the `0.0.5` or above version.
