### ISSUE TITLE
[Bug]: page.waitForResponse results in "Buffer is not defined" error when reading response

### ISSUE THREAD

**Issue by apeacock1991** [cloudflare/puppeteer#18]
### Bug description

Steps to reproduce the problem:

1. …

```
const [res] = await Promise.all([
            page.waitForResponse(res => res.url().includes('something') && res.request().method().toUpperCase() != "OPTIONS"),
            page.goto('https://example.com', {waitUntil: "domcontentloaded"}),
        ]);

console.log(await res?.buffer())
```

You'll need to adjust the URL/matcher, but when you call `res.buffer()` (or .text() or .json()) it raises a `Buffer is not defined` error.

I tested the same code on the core Puppeteer library and it worked fine.

### Puppeteer version

0.0.4

### Node.js version

16

### npm version

9.5.1

### What operating system are you seeing the problem on?

macOS

**Comment by lucaswalter** [comment]
I wanted to share I am getting a very similar error on my worker which was previously working from a few days ago where I take a screenshot of my own site.

```
            browser = await puppeteer.launch(env.OG_IMAGE_BROWSER);
            page = await browser.newPage();
            page.setViewport({ width: 1920, height: 1080, deviceScaleFactor: 2 });

            // Open Game Page
            await page.goto(`https://steambase.io/games/${appId}`);
            await page.waitForSelector('#app-stats-line-chart.loaded');

            // Capture Screenshot
            const img = await page.screenshot({
                type: 'png'
            });
```

This is the error I get when viewing the CF worker logs:
```
    {
      "message": [
        "ReferenceError: Buffer is not defined"
      ],
      "level": "error",
      "timestamp": 1689949193979
    }
```

**Comment by sizovs** [comment]
Same here.

**Comment by bhanderivaibhav** [comment]
mine is failing at initializing browser. 

```
const browser = await puppeteer.launch(env.MYBROWSER);
```

![image](https://github.com/cloudflare/puppeteer/assets/125453483/f0ed59d8-7807-41a7-92b7-e5a7e5c18a4c)

**Comment by AlwaysAwake** [comment]
Same here.

**Comment by denu5** [comment]
update your dependencies incl. node to node 18 lts and try to add: compatibility_flags = [ "nodejs_compat" ]

https://github.com/cloudflare/puppeteer/pull/15#issuecomment-1666001790

**Comment by sizovs** [comment]
@denu5 Thank you. I tried all Node versions from 16 to 19 (with nodejs_compact flag enabled), but it didn't help.

**Comment by cahmetcan** [comment]
I have the same problem even though i enabled nodejs_compact flag

**Comment by roelmagdaleno** [comment]
I had the same problem when initializing the browser and I found a comment in Cloudflare's Discord with this solution:

```js
import { Buffer } from 'node:buffer';
import puppeteer from "@cloudflare/puppeteer";

globalThis.Buffer = Buffer;
```

Basically, import the `Buffer` before `puppeteer` and register globally, so the library can be access from anywhere.

Hope that helps.

**Comment by meddulla** [comment]
@bhanderivaibhav That error can be due to a mismatch between the variable name defined in `wrangler.toml` and the name used in the worker code itself. So, in `wrangler.toml`:

```
browser = { binding = "MY_BROWSER", type = "browser" }
```

and in the worker 

```
export default {
	async fetch(request, env, ctx) {
		const browser = await puppeteer.launch(env.MY_BROWSER); // MUST equal the binding name defined in wrangler 
                 //....
        }
}
```

**Comment by meddulla** [comment]
@apeacock1991 Can you try with the latest versions of wrangler (`3.5.1`) and cloudflare/puppeteer (`0.0.5`)? Can reproduce that error with version `0.0.4` but not with `0.0.5` version. Other things to check out for in `wrangler.toml`:

```
compatibility_date = "2023-05-12"

compatibility_flags = ["nodejs_compat"]
```

**Comment by sizovs** [comment]
The solution by @roelmagdaleno fixed the problem for me. Thank you!
