### ISSUE TITLE
[Bug] Could not resolve "node:buffer"

### ISSUE THREAD

**Issue by vickyRathee** [cloudflare/puppeteer#22]
### Bug description

Getting error on build on Worker as well locally on Wrangler

**Logs from Cloudflare Deployment**

![image](https://github.com/cloudflare/puppeteer/assets/6106479/99390eb5-2e79-4544-8d35-df47bddb1e86)

**Logs from Wrangler**

```
wrangler pages dev --proxy=3000 --compatibility-date=2023-09-04 --local
```

![Error](https://github.com/cloudflare/puppeteer/assets/6106479/0a000852-e040-4f6f-aa73-6fa29f0460e9)

Wrangler.toml
```
# Top-level configuration
name = "puppeteer"
main = "api/server.ts"
node_compat = true
workers_dev = true

browser = { binding = "MYBROWSER" }
```

### Puppeteer version

0.0.5

### Node.js version

18.17.1

### npm version

10.1.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
16:29:00.466 | Found Functions directory at /functions. Uploading.
-- | --
16:29:01.918 | ✘ [ERROR] 3 error(s) and 0 warning(s) when compiling Worker.
16:29:01.919 |  
16:29:01.919 |  
16:29:01.922 |  
16:29:01.924 | ✘ [ERROR] Could not resolve "node:buffer"
16:29:01.924 |  
16:29:01.924 | ../node_modules/@cloudflare/puppeteer/lib/esm/puppeteer/common/Page.js:47:23:
16:29:01.924 | 47 │ import { Buffer } from 'node:buffer';
16:29:01.925 | ╵                        ~~~~~~~~~~~~~
```

**Comment by syonfox** [comment]
Im also unable to use Do you know which version of workers we can use pupatear with.
on debian11 

```sh
npm i @cloudflare/puppeteer

import puppeteer from "@cloudflare/puppeteer";

npx wrangler@2.20.0 pages dev ./public -k kv --log-level debug --compatibility-date=
npx wrangler@2.20.0 pages dev ./public -k kv --log-level debug --compatibility-date=2023-5-5
```



```
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose
▲ [WARNING] No compatibility_date was specified. Using today's date: 2023-11-16.

  Pass it in your terminal:
  ```
  --compatibility-date=2023-11-16
  ```
  See https://developers.cloudflare.com/workers/platform/compatibility-dates/ for more information.

✘ [ERROR] 3 error(s) and 0 warning(s) when compiling Worker.



✘ [ERROR] Could not resolve "node:buffer"

    ../node_modules/@cloudflare/puppeteer/lib/esm/puppeteer/common/Page.js:47:23:
      47 │ import { Buffer } from 'node:buffer';
         ╵                        ~~~~~~~~~~~~~

  The package "node:buffer" wasn't found on the file system but is built into node.
  Add the "nodejs_compat" compatibility flag to your Pages project to enable Node.js compatibility.


✘ [ERROR] Could not resolve "node:stream"

    ../node_modules/@cloudflare/puppeteer/lib/esm/puppeteer/common/util.js:22:25:
      22 │ import { Readable } from 'node:stream';
         ╵                          ~~~~~~~~~~~~~

  The package "node:stream" wasn't found on the file system but is built into node.
  Add the "nodejs_compat" compatibility flag to your Pages project to enable Node.js compatibility.


✘ [ERROR] Could not resolve "node:buffer"

    ../node_modules/@cloudflare/puppeteer/lib/esm/puppeteer/common/util.js:23:23:
      23 │ import { Buffer } from 'node:buffer';
         ╵                        ~~~~~~~~~~~~~

  The package "node:buffer" wasn't found on the file system but is built into node.
  Add the "nodejs_compat" compatibility flag to your Pages project to enable Node.js compatibility.


✘ [ERROR] Build failed with 3 errors:

  ../node_modules/@cloudflare/puppeteer/lib/esm/puppeteer/common/Page.js:47:23: ERROR: Could not
  resolve "node:buffer"
  ../node_modules/@cloudflare/puppeteer/lib/esm/puppeteer/common/util.js:22:25: ERROR: Could not
  resolve "node:stream"
  ../node_modules/@cloudflare/puppeteer/lib/esm/puppeteer/common/util.js:23:23: ERROR: Could not
  resolve "node:buffer"

Process finished with exit code 1

```

**Comment by syonfox** [comment]
Interesting snooping around the dates and flags i was able to get things mostly working it seems the node:stream class was just missing. 

Were you guys poly-filling it yourself?

``` 
npx wrangler@2.20.0 pages dev ./public -k kv --log-level debug --compatibility-date=2023-3.14 --compatibility-flags="nodejs_compat" --port 5601 -b browser

```


✨ Compiled Worker successfully
Retrieving cached values for userId from node_modules/.cache/wrangler
Metrics dispatcher: Dispatching disabled - would have sent {"type":"event","name":"build pages functions","properties":{}}.
 ⛅️ wrangler 2.20.0 (update available 3.15.0)
-------------------------------------------------------
Want to try out the next version of local mode using the open-source Workers runtime?
Switch out --local for --experimental-local and let us know what you think at https://discord.gg/cloudflaredev !
Metrics dispatcher: Dispatching disabled - would have sent {"type":"event","name":"run dev","properties":{"local":true,"usesTypeScript":false}}.
Using vars defined in .dev.vars
Your worker has access to the following bindings:
- KV Namespaces:
  - kv: 
- Vars:
  - browser: "(hidden)"
⎔ Starting a local server...
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [c] clear console, [x] to exit                                                                           │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Debugger listening on ws://127.0.0.1:33043/d8ebff58-5fab-40b8-9945-c809203f011f
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
MINIFLARE OPTIONS:
 {
  "port": 5601,
  "scriptPath": "/tmp/tmp-127990-qjUU52YeQ4OB/functionsWorker-0.1702256215837934.js",
  "https": false,
  "host": "0.0.0.0",
  "modules": true,
  "modulesRules": [
    {
      "type": "Text",
      "include": [
        "**/*.txt",
        "**/*.html"
      ]
    },
    {
      "type": "Data",
      "include": [
        "**/*.bin"
      ]
    },
    {
      "type": "CompiledWasm",
      "include": [
        "**/*.wasm",
        "**/*.wasm?module"
      ]
    }
  ],
  "compatibilityDate": "2023-3.14",
  "compatibilityFlags": [
    "nodejs_compat"
  ],
  "kvNamespaces": [
    "kv"
  ],
  "queueBindings": [],
  "queueConsumers": [],
  "r2Buckets": [],
  "durableObjects": {},
  "externalDurableObjects": {},
  "d1Databases": [],
  "cachePersist": true,
  "durableObjectsPersist": true,
  "kvPersist": true,
  "r2Persist": true,
  "d1Persist": true,
  "liveReload": false,
  "bindings": {
    "browser": ""
  },
  "wasmBindings": {},
  "textBlobBindings": {},
  "dataBlobBindings": {},
  "sourceMap": true,
  "logUnhandledRejections": true,
  "crons": [],
  "logLevel": "debug",
  "enablePagesAssetsServiceBinding": {
    "directory": "/home/mango/git/sgol.pub/public"
  },
  "globalAsyncIO": true,
  "globalRandom": true,
  "globalTimers": true,
  "log": {
    "level": 4
  }
}
[mf:dbg] Initialising worker...
[mf:dbg] Options:
[mf:dbg] - Script Path: /tmp/tmp-127990-qjUU52YeQ4OB/functionsWorker-0.1702256215837934.js
[mf:dbg] - Modules: true
[mf:dbg] - Modules Rules: {Text: **/*.txt, **/*.html}, {Data: **/*.bin}, {CompiledWasm: **/*.wasm, **/*.wasm?module}
[mf:dbg] - Compatibility Date: 2023-3.14
[mf:dbg] - Compatibility Flags: nodejs_compat
[mf:dbg] - Allow Global Async I/O: true
[mf:dbg] - Allow Global Timers: true
[mf:dbg] - Allow Global Secure Random: true
[mf:dbg] - Host: 0.0.0.0
[mf:dbg] - Port: 5601
[mf:dbg] - HTTPS: false
[mf:dbg] - Live Reload: false
[mf:dbg] - CRON Expressions: 
[mf:dbg] - KV Namespaces: kv
[mf:dbg] - KV Persistence: true
[mf:dbg] - D1 Namespaces: 
[mf:dbg] - D1 Persistence: true
[mf:dbg] - R2 Buckets: 
[mf:dbg] - R2 Persistence: true
[mf:dbg] - Durable Objects: 
[mf:dbg] - Durable Objects Persistence: true
[mf:dbg] - Cache Persistence: true
[mf:dbg] - Queue Bindings: 
[mf:dbg] - Queue Consumers: 
[mf:dbg] - Custom Bindings: browser
[mf:dbg] - WASM Bindings: 
[mf:dbg] - Text Blob Bindings: 
[mf:dbg] - Data Blob Bindings: 
[mf:dbg] - Service Bindings: ASSETS
[mf:dbg] Enabled Compatibility Flags:
[mf:dbg] - nodejs_compat
[mf:dbg] - streams_enable_constructors
[mf:dbg] - transformstream_enable_standard_constructor
[mf:dbg] - export_commonjs_default
[mf:dbg] - r2_list_honor_include
[mf:dbg] - global_navigator
[mf:dbg] - durable_object_fetch_requires_full_url
[mf:dbg] - fetch_refuses_unknown_protocols
[mf:dbg] - formdata_parser_supports_files
[mf:wrn] Service bindings are experimental. There may be breaking changes in the future.
[mf:dbg] Reloading worker...
[mf:err] VMScriptRunnerError [ERR_MODULE_RULE]: Unable to resolve "functionsWorker-0.1702256215837934.js" dependency "node:stream": no matching module rules.
If you're trying to import an npm package, you'll need to bundle your Worker first.
    at linker (/home/mango/.asdf/installs/nodejs/16.20.2/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/linker.ts:101:13)
    at ModuleWrap.<anonymous> (node:internal/vm/module:315:30)
    at SourceTextModule.<computed> (node:internal/vm/module:314:36)
    at SourceTextModule.link (node:internal/vm/module:199:22)
    at VMScriptRunner.runAsModule (/home/mango/.asdf/installs/nodejs/16.20.2/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/index.ts:39:18)
    at VMScriptRunner.run (/home/mango/.asdf/installs/nodejs/16.20.2/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/index.ts:86:28)
    at EventTarget.#reload (/home/mango/.asdf/installs/nodejs/16.20.2/lib/node_modules/wrangler/node_modules/@miniflare/core/src/index.ts:790:42)
    at EventTarget.getPlugins (/home/mango/.asdf/installs/nodejs/16.20.2/lib/node_modules/wrangler/node_modules/@miniflare/core/src/index.ts:1033:5)
    at createServer (/home/mango/.asdf/installs/nodejs/16.20.2/lib/node_modules/wrangler/node_modules/@miniflare/http-server/src/index.ts:362:19)
    at startServer (/home/mango/.asdf/installs/nodejs/16.20.2/lib/node_modules/wrangler/node_modules/@miniflare/http-server/src/index.ts:469:18)
VMScriptRunnerError [ERR_MODULE_RULE]: Unable to resolve "functionsWorker-0.1702256215837934.js" dependency "node:stream": no matching module rules.
If you're trying to import an npm package, you'll need to bundle your Worker first.
    at linker (/home/mango/.asdf/installs/nodejs/16.20.2/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/linker.ts:101:13)
    at ModuleWrap.<anonymous> (node:internal/vm/module:315:30)
    at SourceTextModule.<computed> (node:internal/vm/module:314:36)
    at SourceTextModule.link (node:internal/vm/module:199:22)
    at VMScriptRunner.runAsModule (/home/mango/.asdf/installs/nodejs/16.20.2/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/index.ts:39:18)
    at VMScriptRunner.run (/home/mango/.asdf/installs/nodejs/16.20.2/lib/node_modules/wrangler/node_modules/@miniflare/runner-vm/src/index.ts:86:28)
    at EventTarget.#reload (/home/mango/.asdf/installs/nodejs/16.20.2/lib/node_modules/wrangler/node_modules/@miniflare/core/src/index.ts:790:42)
    at EventTarget.getPlugins (/home/mango/.asdf/installs/nodejs/16.20.2/lib/node_modules/wrangler/node_modules/@miniflare/core/src/index.ts:1033:5)
    at createServer (/home/mango/.asdf/installs/nodejs/16.20.2/lib/node_modules/wrangler/node_modules/@miniflare/http-server/src/index.ts:362:19)
    at startServer (/home/mango/.asdf/installs/nodejs/16.20.2/lib/node_modules/wrangler/node_modules/@miniflare/http-server/src/index.ts:469:18)
Waiting for the debugger to disconnect...
⎔ Shutting down local server.


```

**Comment by meddulla** [comment]
Yes, read more about it [here](https://developers.cloudflare.com/workers/runtime-apis/nodejs).

**Comment by syonfox** [comment]
Hmm changed to node 18 but still no progress, can update the polyfills 

```
VMScriptRunnerError [ERR_MODULE_RULE]: Unable to resolve "functionsWorker-0.4210887901632061.js" dependency "node:stream": no matching module rules.


   at Miniflare.getPlugins (/home/mango/.npm/_npx/7eabd05301f46f47/node_modules/@miniflare/core/src/index.ts:1033:5)
    at createServer (/home/mango/.npm/_npx/7eabd05301f46f47/node_modules/@miniflare/http-server/src/index.ts:362:19)
    at startServer (/home/mango/.npm/_npx/7eabd05301f46f47/node_modules/@miniflare/http-server/src/index.ts:469:18)

```

looks like somthings wrong with this version of miniflare with these settings

## yay was able to get it to not crash next step can you even attach the browser bindings to dev environment in pages. how do you get this working in the pages function in productions

@meddulla Is it possible to attach pupateer browsers to development pages like so?

also is browser functionality available on paid workers plan or did i see correctly somewhere that you need a paid 0 trust plan for it to be available. 

```
npx wrangler pages dev ./public -k kv --log-level debug --compatibility-date=2023-3.14 --compatibility-flags="nodejs_compat" --port 5901 -b browser 
Need to install the following packages:
  wrangler@3.15.0
Ok to proceed? (y) y

 ⛅️ wrangler 3.15.0
-------------------
Metrics dispatcher: Dispatching disabled - would have sent {"type":"event","name":"run dev","properties":{"local":true,"usesTypeScript":false}}.
Using vars defined in .dev.vars
Your worker has access to the following bindings:
- KV Namespaces:
  - kv: kv
- Vars:
  - browser: "(hidden)"
⎔ Starting local server...
[mf:dbg] Updated `Request.cf` object cache!
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [c] clear console, [x] to exit         
```

**Comment by meddulla** [comment]
@syonfox You need to ask for access [here](https://www.cloudflare.com/en-gb/lp/workers-browser-rendering-api/) or in [discord](https://discord.com/channels/595317990191398933/1112675059174219866).

**Comment by adrianotadao** [comment]
hey @vickyRathee, how did you make it work? :D
