### ISSUE TITLE
Upstream fixes/features syncing

### ISSUE THREAD

**Issue by Cherry** [cloudflare/puppeteer#36]
It seems like this fork of puppeteer is based on `v17.0.0` (released August 2022), whereas the latest version is `v22.6.3` (released yesterday, April 2024)

Specifically, I'm looking to get deeper JS coverage information (by function scope), which has been possible since puppeteer v19, but not here, at least not according to the types for `JSCoverageOptions` missing `useBlockCoverage`.

What is the plan to keep this up to date with upstream puppeteer changes?

**Comment by meddulla** [comment]
Can't commit to a specific release schedule for now but we'll be updating to v19 in the next few months.

**Comment by danielgek** [comment]
@Cherry new release is out 🥳 

You should now have js coverage apis available available
