### ISSUE TITLE
[Bug]: page.screenshot with a width set via setViewport, returns an image px narrower than expected

### ISSUE THREAD

**Issue by KoanLeeroy** [cloudflare/puppeteer#41]
### Bug description

Steps to reproduce the problem:

```
const page = await browser.newPage();
await page.setCacheEnabled(false);
await page.setViewport({ width: 1000, height: 1 });
const response = await page.goto("https://www.google.com");

await page.screenshot({ fullPage: true, omitBackground: true });
```

The screenshot returned is 990px wide. Other URL's exhibit the same behaviour.

### Puppeteer version

latest Cloudflare puppeteer version

### Node.js version

Workers

### npm version

Workers

### What operating system are you seeing the problem on?

Linux

**Comment by danielgek** [comment]
@KoanLeeroy and @rahulkumarsingh73690 fixed in the latest release
