### ISSUE TITLE
[Bug]: Invalid URL `/v1/acquire` thrown from `PuppeteerWorkers.launch`

### ISSUE THREAD

**Issue by hmnd** [cloudflare/puppeteer#50]
### Bug description

Steps to reproduce the problem:

1. Create worker following the guide [here](https://developers.cloudflare.com/browser-rendering/get-started/screenshots/).
2. Try to make a request to the worker.

### Puppeteer version

0.0.10

### Node.js version

20.13.1

### npm version

10.5.2

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
✘ [ERROR] Uncaught (in response) TypeError: Invalid URL: /v1/acquire

      at PuppeteerWorkers.launch
```

**Comment by meddulla** [comment]
Hi @hmnd Can't reproduce and the API hasn't changed. Can you provide your wrangler.toml + js/ts file in a gist?

**Comment by hmnd** [comment]
@meddulla thanks for the quick response. Here you go :) https://gist.github.com/hmnd/5f6e7810c6e1feb8b5b66dab57769116

**Comment by sunneydev** [comment]
@meddulla seems like base url for the fetch is not defined. i also get type errors with current latest versions on everything.

its for some reason colliding with `undici-types`, even though i don't have `@types/node`.
![image](https://github.com/cloudflare/puppeteer/assets/55714870/d3ad7613-f5f3-47fd-9adf-45582cfea5a8)
![image](https://github.com/cloudflare/puppeteer/assets/55714870/0978c197-1afd-4b5c-98ce-72fd2430be04)
![image](https://github.com/cloudflare/puppeteer/assets/55714870/95254730-f112-4491-add8-655106aeb176)

**Comment by meddulla** [comment]
@hmnd @sunneydev  Thanks. Can reproduce now. The issue seems to be related to the `compatibility_date`. Can you both try and set the compatibility_date to `2024-06-02` or less?

**Comment by abdullah** [comment]
Updating `compatibility_date` works for me 🚀

**Comment by meddulla** [comment]
Latest version`0.0.11` fixes this.
