### ISSUE TITLE
[Bug]: Browser is closed despite having set keep_alive setting to 10mins

### ISSUE THREAD

**Issue by cloudkite** [cloudflare/puppeteer#53]
### Bug description

Steps to reproduce the problem:

1. Minimal reproduction see https://github.com/cloudkite/keep-alive-test. Have got a simple worker which crawls https://example.com every 5mins. Browser is launched with 10min keep_alive.
2. After around 11 mins the browser is closed with the reason "Browser idle".
3. Would expect the browser to only close if the last connection time was greater than 10mins ago

![CleanShot 2024-07-17 at 08 24 49@2x](https://github.com/user-attachments/assets/60bf537d-8f41-4652-ab6d-89fe788352aa)

### Puppeteer version

0.0.11

**Comment by meddulla** [comment]
Hi @cloudkite The `keep-alive` option allows browsers to be kept alive for the initial 10 minutes, even if totally idle. After that the idle time is reset to the default of 1 minute. This is to maximise browser utilisation.  But I do understand this might be confusing and we'll make it clearer in the documentation. We _might_ revisit this decision in the future when we can increase the current limits per account but no promises.

**Comment by cloudkite** [comment]
Thanks for clarifying. Seems like a weird constraint to put on the API, especially since when using the DO way of keeping browser alive you can get a rolling 10min idle time. Rather the  idle time which resets back to 1min.
