### ISSUE TITLE
[Bug]: connect no longer supports browserWSEndpoint

### ISSUE THREAD

**Issue by cloudkite** [cloudflare/puppeteer#73]
### Minimal, reproducible example

```TypeScript
await puppeteer.connect({ browserWSEndpoint })
```

### Error string

An argument for 'sessionId' was not provided.

### Expectation

this worked in 0.0.11 see https://github.com/cloudflare/puppeteer/pull/43

**Comment by danielgek** [comment]
@cloudkite can you install @cloudflare/puppeteer@next and try it out ?

**Comment by cloudkite** [comment]
@danielgek thanks so much, can confirm its working again for me on 0.0.14-rc

**Comment by danielgek** [comment]
@cloudkite released version `0.0.14`
