### ISSUE TITLE
[Bug]: connect using browserWSEndpoint

### ISSUE THREAD

**Issue by Kikobeats** [cloudflare/puppeteer#78]
### Minimal, reproducible example

```TypeScript
;(async () => {
  // server-side
  const puppeteer = require('puppeteer')
  const browser = await puppeteer.launch();
  const browserWSEndpoint = browser.wsEndpoint();

  // client-side
  const cloudFlarePuppeteer = require('@cloudflare/puppeteer')
  const puppeterBrowser = await cloudFlarePuppeteer.launch({browserWSEndpoint});
  console.log(puppeterBrowser)

  // teardown
  await browser.close()
})()
```

### Error string

I was expecting this to may possible, but it seems websockets connection is not supoprted. There is nothing about that in readme. Can you please clarify? 🙏

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Expectation

connect against browser websocket endpoint

### Reality

It's not working.

### Puppeteer version

23.3.0

### Node version

20.17.0.

### Package manager

pnpm

### Package manager version

9.8.0

### Operating system

macOS

**Comment by danielgek** [comment]
@Kikobeats you can use the `browserWSEndpoint` in the following way:

```ts
const browserWSEndpoint = 'your-ws-endpoint-here'
await puppeteer.connect({ browserWSEndpoint })

```

**Comment by Kikobeats** [comment]
Oh, my fault. Thanks!
