### ISSUE TITLE
[Bug]: "Failed to execute 'open' on 'IDBFactory': access to the Indexed Database API is denied in this context."

### ISSUE THREAD

**Issue by ambrt** [cloudflare/puppeteer#85]
### Minimal, reproducible example

```TypeScript
await page.evaluate(() => {
try{
    var openReq = indexedDB.open('test_db', 1);
}catch(err){
    console.log(err.message)
}
})
```

### Error string

"Failed to execute 'open' on 'IDBFactory': access to the Indexed Database API is denied in this context."

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I've been trying to save info between Browser Rendering sessions, into indexedDB, so i could use it in new request with the same session id ("Reusing sessions" in docs).

### Expectation

I expected to open indexedDB database in Browser Rendering

### Reality

Its not allowed.

### Puppeteer version

latest

### Node version

20.04

### Package manager

npm

### Package manager version

9.7.2

### Operating system

Linux

**Comment by danielgek** [comment]
@ambrt can you expand your code example, i tested this locally and i cannot repro

**Comment by danielgek** [comment]
@ambrt good find and indeed seams like chrome only supports indexedDB and localstorage when you are on a domain, you can use [https://example.com/](https://example.com/) or [https://blank.org/](https://blank.org/) if this workaround does not fit your use case let me know
